CREATE TABLE Product(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  Brand VARCHAR(64) NOT NULL,
  PRICE BIGINT NOT NULL,
  IMAGE VARCHAR(640) NOT NULL
);

CREATE TABLE CUSTOMER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(64) NOT NULL,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) NOT NULL,
  EMAIL NCHAR(64) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  ADDRESS VARCHAR(64) NOT NULL
);

--CREATE TABLE CUSTOMER(
--ID BIGINT AUTO_INCREMENT PRIMARY KEY,
--  FIRST_NAME VARCHAR(64),
  --LAST_NAME VARCHAR(64),
  --EMAIL_ADDRESS VARCHAR(64),
  --PASSWORD VARCHAR(64)
--);
